/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;

import javax.swing.JFrame;
import model.*;
import DAO.NhanVienDAO;
import javax.swing.JOptionPane;

/**
 *
 * @author truong
 */
public class DoiMatKhauJDialog extends javax.swing.JDialog {

    NhanVienDAO nvDAO = new NhanVienDAO();
    CheckData data = new CheckData();
    MessageNotifycation mess = new MessageNotifycation();
   

    /**
     * Creates new form DoiMatKhauJDialog
     */
    public DoiMatKhauJDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        this.setTitle("Doi Mat Khau");
        this.setIconImage(CreateFormat.getImageApp());
    }

    public boolean checkForm() {
        if (!data.checkIsEmpty(txtUsername)) {
            data.changColorLabel(false, lblerrUser, "User is not empty");
            return false;
        } else {
            data.changColorLabel(true, lblerrUser, null);
        }
        if (!data.checkIsEmpty(txtCurrentPasword)) {
            data.changColorLabel(false, lblErrcurentpass, "Current Password is not empty");
            return false;
        } else {
            data.changColorLabel(true, lblErrcurentpass, null);
        }
        if (!data.checkIsEmpty(txtNewpassword)) {
            data.changColorLabel(false, lblerrNewpass, "New password is not empty");
            return false;
        } else {
            data.changColorLabel(true, lblerrNewpass, null);
        }
        if (!data.checkIsEmpty(txtConfirmPass)) {
            data.changColorLabel(false, lblerrConfirmpass, "Confirm password is not empty");
            return false;
        } else {
            data.changColorLabel(true, lblerrConfirmpass, null);
        }
        return true;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlBackground = new javax.swing.JPanel();
        lblChangePass = new javax.swing.JLabel();
        lblUsername = new javax.swing.JLabel();
        lblNewpass = new javax.swing.JLabel();
        lblCurrentPass = new javax.swing.JLabel();
        lblConfirm = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        txtCurrentPasword = new javax.swing.JTextField();
        txtConfirmPass = new javax.swing.JPasswordField();
        txtNewpassword = new javax.swing.JPasswordField();
        btnRegister = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        lblerrUser = new javax.swing.JLabel();
        lblErrcurentpass = new javax.swing.JLabel();
        lblerrNewpass = new javax.swing.JLabel();
        lblerrConfirmpass = new javax.swing.JLabel();
        chkshow = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        pnlBackground.setBackground(new java.awt.Color(255, 153, 51));

        javax.swing.GroupLayout pnlBackgroundLayout = new javax.swing.GroupLayout(pnlBackground);
        pnlBackground.setLayout(pnlBackgroundLayout);
        pnlBackgroundLayout.setHorizontalGroup(
            pnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 186, Short.MAX_VALUE)
        );
        pnlBackgroundLayout.setVerticalGroup(
            pnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        lblChangePass.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblChangePass.setForeground(new java.awt.Color(102, 204, 0));
        lblChangePass.setText("Change Password");

        lblUsername.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblUsername.setText("Username : ");

        lblNewpass.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblNewpass.setText("New Password :");

        lblCurrentPass.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblCurrentPass.setText("Current password :");

        lblConfirm.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblConfirm.setText("Confirm New Password : ");

        txtCurrentPasword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCurrentPaswordActionPerformed(evt);
            }
        });

        btnRegister.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/User-Interface-Login-icon.png"))); // NOI18N
        btnRegister.setText("Register");
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });

        btnCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Close-Window-icon.png"))); // NOI18N
        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        lblerrUser.setText(" ");

        lblErrcurentpass.setText(" ");

        lblerrNewpass.setText(" ");

        lblerrConfirmpass.setText(" ");

        chkshow.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        chkshow.setText("Show");
        chkshow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkshowActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNewpass)
                    .addComponent(txtUsername)
                    .addComponent(txtNewpassword, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE)
                    .addComponent(lblChangePass, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblerrUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblerrNewpass, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lblCurrentPass, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblConfirm)
                        .addComponent(txtCurrentPasword, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btnRegister)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnCancel))
                        .addComponent(txtConfirmPass, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE)
                        .addComponent(lblErrcurentpass, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblerrConfirmpass, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(chkshow, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(84, 84, 84)
                .addComponent(pnlBackground, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(lblChangePass, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUsername)
                    .addComponent(lblCurrentPass))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCurrentPasword, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblerrUser)
                    .addComponent(lblErrcurentpass))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNewpass)
                    .addComponent(lblConfirm))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtConfirmPass, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNewpassword, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblerrNewpass)
                    .addComponent(lblerrConfirmpass))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(chkshow)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegister)
                    .addComponent(btnCancel))
                .addGap(33, 33, 33))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCurrentPaswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCurrentPaswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCurrentPaswordActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
        if (checkForm()) {
            String user = txtUsername.getText();
            String pass = txtCurrentPasword.getText();
            String newPass = new String(txtNewpassword.getPassword());
            String confirmPass = new String(txtConfirmPass.getPassword());
            if (!user.equals(Authentication.user.getMaNV())) {
                data.changColorLabel(false, lblerrUser, "User is not exist");
            }else if(!pass.equals(Authentication.user.getMatKhau())){
                data.changColorLabel(false, lblErrcurentpass, "Current Password is wrong");
            }else if(!newPass.equals(confirmPass)){
                    mess.messageNotify(this, "Please enter correct password ", "Error");
            }else{
                if(mess.confirmMessage(this,"Do you want to change password", "Change Password") == JOptionPane.YES_OPTION){
                    Authentication.user.setMatKhau(newPass);
                    nvDAO.update(Authentication.user);
                    mess.messageNotify(this, "Chang Password successfull", "Successful");
            }
            }

        }
    }//GEN-LAST:event_btnRegisterActionPerformed

    private void chkshowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkshowActionPerformed

        txtNewpassword.setEchoChar((char)0);
        txtConfirmPass.setEchoChar((char)0);
    }//GEN-LAST:event_chkshowActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("FlatLaf Light".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DoiMatKhauJDialog.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DoiMatKhauJDialog.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DoiMatKhauJDialog.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DoiMatKhauJDialog.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DoiMatKhauJDialog dialog = new DoiMatKhauJDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnRegister;
    private javax.swing.JCheckBox chkshow;
    private javax.swing.JLabel lblChangePass;
    private javax.swing.JLabel lblConfirm;
    private javax.swing.JLabel lblCurrentPass;
    private javax.swing.JLabel lblErrcurentpass;
    private javax.swing.JLabel lblNewpass;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JLabel lblerrConfirmpass;
    private javax.swing.JLabel lblerrNewpass;
    private javax.swing.JLabel lblerrUser;
    private javax.swing.JPanel pnlBackground;
    private javax.swing.JPasswordField txtConfirmPass;
    private javax.swing.JTextField txtCurrentPasword;
    private javax.swing.JPasswordField txtNewpassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
