/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import com.google.zxing.BarcodeFormat;
import com.google.zxing.client.j2se.MatrixToImageWriter;
import com.google.zxing.common.BitMatrix;
import com.google.zxing.qrcode.QRCodeWriter;
import java.awt.Desktop;
import java.io.File;
import java.nio.file.FileSystems;
import java.nio.file.Path;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import model.*;

/**
 *
 * @author truong
 */
public class EduSys extends javax.swing.JFrame implements Runnable {

    MessageNotifycation mess = new MessageNotifycation();
   
    
    /**
     * Creates new form EduSys
     */
    public EduSys() {
        initComponents();
        initFrame();
        autoImage();


    }
    public void autoImage() {
        // D:\DuAnMauJava\EduSys\Logos
        String[] img = {"JAVA-ONLINE.png",  "lap-trinh-web-la-gi.jpg","lo-trinh-fe_zzhxml.png"};
        new Thread(() -> {
            int i = 0;
            while (true) {
                lblBanner.setIcon(Ximage.read(img[i],lblBanner));
                try {
                    Thread.sleep(2000);
                } catch (InterruptedException ex) {
                    Logger.getLogger(EduSys.class.getName()).log(Level.SEVERE, null, ex);
                }
                i++;
                if (i > img.length - 1) {
                    i = 0;
                }
            }
        }).start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        btnLogout = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JToolBar.Separator();
        btnExit = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        btnChuyenDe = new javax.swing.JButton();
        btnNguoiHoc = new javax.swing.JButton();
        btnKhoaHoc = new javax.swing.JButton();
        btnHocVien = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        btnHoTro = new javax.swing.JButton();
        pnlFooter = new javax.swing.JPanel();
        lblGioiThieu = new javax.swing.JLabel();
        lblClock = new javax.swing.JLabel();
        lblUser = new javax.swing.JLabel();
        lblBanner = new javax.swing.JLabel();
        mnbMain = new javax.swing.JMenuBar();
        mnuSystem = new javax.swing.JMenu();
        mniLogIn = new javax.swing.JMenuItem();
        mniLogout = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        mniChangePass = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        mniExit = new javax.swing.JMenuItem();
        mnuManager = new javax.swing.JMenu();
        mnuChuyenDe = new javax.swing.JMenuItem();
        mniKhoaHoc = new javax.swing.JMenuItem();
        mniNguoiHoc = new javax.swing.JMenuItem();
        mniHocVien = new javax.swing.JMenuItem();
        jSeparator6 = new javax.swing.JPopupMenu.Separator();
        mniNhanVien = new javax.swing.JMenuItem();
        mnuStatissic = new javax.swing.JMenu();
        mniBangDiem = new javax.swing.JMenuItem();
        jSeparator7 = new javax.swing.JPopupMenu.Separator();
        mniLuotNH = new javax.swing.JMenuItem();
        mniDiemCD = new javax.swing.JMenuItem();
        mniDoanhThu = new javax.swing.JMenuItem();
        mnuSupport = new javax.swing.JMenu();
        mniHDSD = new javax.swing.JMenuItem();
        mniGTSP = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jToolBar1.setRollover(true);

        btnLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/User-Interface-Login-icon.png"))); // NOI18N
        btnLogout.setText("Dang Xuat");
        btnLogout.setFocusable(false);
        btnLogout.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnLogout.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });
        jToolBar1.add(btnLogout);
        jToolBar1.add(jSeparator4);

        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Close-2-icon.png"))); // NOI18N
        btnExit.setText("Thoat");
        btnExit.setFocusable(false);
        btnExit.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnExit.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        jToolBar1.add(btnExit);
        jToolBar1.add(jSeparator1);

        btnChuyenDe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/folder-documents-icon.png"))); // NOI18N
        btnChuyenDe.setText("Chuyen De");
        btnChuyenDe.setFocusable(false);
        btnChuyenDe.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnChuyenDe.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnChuyenDe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChuyenDeActionPerformed(evt);
            }
        });
        jToolBar1.add(btnChuyenDe);

        btnNguoiHoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Users-icon.png"))); // NOI18N
        btnNguoiHoc.setText("Nguoi Hoc");
        btnNguoiHoc.setFocusable(false);
        btnNguoiHoc.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNguoiHoc.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnNguoiHoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNguoiHocActionPerformed(evt);
            }
        });
        jToolBar1.add(btnNguoiHoc);

        btnKhoaHoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Courses-icon.png"))); // NOI18N
        btnKhoaHoc.setText("Khoa Hoc");
        btnKhoaHoc.setFocusable(false);
        btnKhoaHoc.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnKhoaHoc.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnKhoaHoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKhoaHocActionPerformed(evt);
            }
        });
        jToolBar1.add(btnKhoaHoc);

        btnHocVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Student-id-icon.png"))); // NOI18N
        btnHocVien.setText("Hoc Vien");
        btnHocVien.setFocusable(false);
        btnHocVien.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnHocVien.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnHocVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHocVienActionPerformed(evt);
            }
        });
        jToolBar1.add(btnHocVien);
        jToolBar1.add(jSeparator2);

        btnHoTro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Help-icon.png"))); // NOI18N
        btnHoTro.setText("Ho Tro");
        btnHoTro.setFocusable(false);
        btnHoTro.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnHoTro.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnHoTro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHoTroActionPerformed(evt);
            }
        });
        jToolBar1.add(btnHoTro);

        lblGioiThieu.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        lblGioiThieu.setForeground(new java.awt.Color(255, 153, 51));
        lblGioiThieu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/student-icon.png"))); // NOI18N
        lblGioiThieu.setText("Education System Manager");

        lblClock.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        lblClock.setForeground(new java.awt.Color(255, 153, 51));
        lblClock.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Apps-clock-icon.png"))); // NOI18N

        lblUser.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        lblUser.setForeground(new java.awt.Color(255, 51, 51));
        lblUser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUser.setText(" ");

        javax.swing.GroupLayout pnlFooterLayout = new javax.swing.GroupLayout(pnlFooter);
        pnlFooter.setLayout(pnlFooterLayout);
        pnlFooterLayout.setHorizontalGroup(
            pnlFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFooterLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblGioiThieu, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(260, 260, 260)
                .addComponent(lblUser, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 344, Short.MAX_VALUE)
                .addComponent(lblClock, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        pnlFooterLayout.setVerticalGroup(
            pnlFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblGioiThieu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlFooterLayout.createSequentialGroup()
                .addGroup(pnlFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlFooterLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblClock, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(lblUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        lblBanner.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBanner.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/JAVA-ONLINE.png"))); // NOI18N
        lblBanner.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblBannerMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblBannerMouseExited(evt);
            }
        });

        mnuSystem.setForeground(new java.awt.Color(255, 102, 0));
        mnuSystem.setText("System");

        mniLogIn.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mniLogIn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Status-dialog-password-icon.png"))); // NOI18N
        mniLogIn.setText("Dang Nhap");
        mniLogIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniLogInActionPerformed(evt);
            }
        });
        mnuSystem.add(mniLogIn);

        mniLogout.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mniLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/logout-icon.png"))); // NOI18N
        mniLogout.setText("Dang Xuat");
        mniLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniLogoutActionPerformed(evt);
            }
        });
        mnuSystem.add(mniLogout);
        mnuSystem.add(jSeparator5);

        mniChangePass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Status-dialog-password-icon.png"))); // NOI18N
        mniChangePass.setText("Doi Mat Khau");
        mniChangePass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniChangePassActionPerformed(evt);
            }
        });
        mnuSystem.add(mniChangePass);
        mnuSystem.add(jSeparator3);

        mniExit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F10, 0));
        mniExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Close-2-icon.png"))); // NOI18N
        mniExit.setText("Thoat");
        mniExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniExitActionPerformed(evt);
            }
        });
        mnuSystem.add(mniExit);

        mnbMain.add(mnuSystem);

        mnuManager.setForeground(new java.awt.Color(255, 102, 0));
        mnuManager.setText("Manger");

        mnuChuyenDe.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mnuChuyenDe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/folder-documents-icon.png"))); // NOI18N
        mnuChuyenDe.setText("Chuyen De");
        mnuChuyenDe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuChuyenDeActionPerformed(evt);
            }
        });
        mnuManager.add(mnuChuyenDe);

        mniKhoaHoc.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F2, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mniKhoaHoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Courses-icon.png"))); // NOI18N
        mniKhoaHoc.setText("Khoa Hoc");
        mniKhoaHoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniKhoaHocActionPerformed(evt);
            }
        });
        mnuManager.add(mniKhoaHoc);

        mniNguoiHoc.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F3, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mniNguoiHoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Users-icon.png"))); // NOI18N
        mniNguoiHoc.setText("Nguoi Hoc");
        mniNguoiHoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniNguoiHocActionPerformed(evt);
            }
        });
        mnuManager.add(mniNguoiHoc);

        mniHocVien.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mniHocVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Student-id-icon.png"))); // NOI18N
        mniHocVien.setText("Hoc Vien");
        mniHocVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniHocVienActionPerformed(evt);
            }
        });
        mnuManager.add(mniHocVien);
        mnuManager.add(jSeparator6);

        mniNhanVien.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F5, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mniNhanVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Preppy-icon.png"))); // NOI18N
        mniNhanVien.setText("Nhan Vien");
        mniNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniNhanVienActionPerformed(evt);
            }
        });
        mnuManager.add(mniNhanVien);

        mnbMain.add(mnuManager);

        mnuStatissic.setForeground(new java.awt.Color(255, 102, 0));
        mnuStatissic.setText("Statistic");

        mniBangDiem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        mniBangDiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Generate-tables-icon.png"))); // NOI18N
        mniBangDiem.setText("Bang Diem");
        mniBangDiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniBangDiemActionPerformed(evt);
            }
        });
        mnuStatissic.add(mniBangDiem);
        mnuStatissic.add(jSeparator7);

        mniLuotNH.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F2, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        mniLuotNH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Finance-Purchase-Order-icon.png"))); // NOI18N
        mniLuotNH.setText("Luot Nguoi Hoc");
        mniLuotNH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniLuotNHActionPerformed(evt);
            }
        });
        mnuStatissic.add(mniLuotNH);

        mniDiemCD.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F3, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        mniDiemCD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Actions-view-list-text-icon.png"))); // NOI18N
        mniDiemCD.setText("Diem Chuyen De");
        mniDiemCD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniDiemCDActionPerformed(evt);
            }
        });
        mnuStatissic.add(mniDiemCD);

        mniDoanhThu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        mniDoanhThu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/coins-icon.png"))); // NOI18N
        mniDoanhThu.setText("Danh Thu");
        mniDoanhThu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniDoanhThuActionPerformed(evt);
            }
        });
        mnuStatissic.add(mniDoanhThu);

        mnbMain.add(mnuStatissic);

        mnuSupport.setForeground(new java.awt.Color(255, 102, 0));
        mnuSupport.setText("Support");

        mniHDSD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Finance-Card-In-Use-icon.png"))); // NOI18N
        mniHDSD.setText("Huong Dan Su Dung");
        mniHDSD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniHDSDActionPerformed(evt);
            }
        });
        mnuSupport.add(mniHDSD);

        mniGTSP.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        mniGTSP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Actions-help-about-icon.png"))); // NOI18N
        mniGTSP.setText("Gioi Thieu San Pham");
        mniGTSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniGTSPActionPerformed(evt);
            }
        });
        mnuSupport.add(mniGTSP);

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/qr.png"))); // NOI18N
        jMenuItem1.setText("QRCode");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        mnuSupport.add(jMenuItem1);

        mnbMain.add(mnuSupport);

        setJMenuBar(mnbMain);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(pnlFooter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblBanner)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblBanner, javax.swing.GroupLayout.PREFERRED_SIZE, 581, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(pnlFooter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        Exit();
    }//GEN-LAST:event_btnExitActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        Thread t = new Thread(this);
        t.start();

    }//GEN-LAST:event_formWindowOpened

    private void mniLuotNHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniLuotNHActionPerformed
        openThongKe(1);
    }//GEN-LAST:event_mniLuotNHActionPerformed

    private void mniGTSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniGTSPActionPerformed
        openGioiThieu();

    }//GEN-LAST:event_mniGTSPActionPerformed

    private void mniExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniExitActionPerformed
        Exit();
    }//GEN-LAST:event_mniExitActionPerformed

    private void mniChangePassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniChangePassActionPerformed
        openChangePassword();
    }//GEN-LAST:event_mniChangePassActionPerformed

    private void mniLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniLogoutActionPerformed
        Logout();
    }//GEN-LAST:event_mniLogoutActionPerformed

    private void mnuChuyenDeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuChuyenDeActionPerformed
        openChuyenDe();
    }//GEN-LAST:event_mnuChuyenDeActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        Logout();
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void mniLogInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniLogInActionPerformed
        openLogin();
    }//GEN-LAST:event_mniLogInActionPerformed

    private void mniKhoaHocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniKhoaHocActionPerformed
        openKhoaHoc();
    }//GEN-LAST:event_mniKhoaHocActionPerformed

    private void mniNguoiHocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniNguoiHocActionPerformed
        openNguoiHoc();
    }//GEN-LAST:event_mniNguoiHocActionPerformed

    private void mniHocVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniHocVienActionPerformed
        openHocVien();
    }//GEN-LAST:event_mniHocVienActionPerformed

    private void mniNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniNhanVienActionPerformed
        openNhanVien();
    }//GEN-LAST:event_mniNhanVienActionPerformed

    private void btnChuyenDeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChuyenDeActionPerformed
        openChuyenDe();
    }//GEN-LAST:event_btnChuyenDeActionPerformed

    private void btnNguoiHocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNguoiHocActionPerformed
        openNguoiHoc();
    }//GEN-LAST:event_btnNguoiHocActionPerformed

    private void btnKhoaHocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKhoaHocActionPerformed
        openKhoaHoc();
    }//GEN-LAST:event_btnKhoaHocActionPerformed

    private void btnHocVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHocVienActionPerformed
        openHocVien();
    }//GEN-LAST:event_btnHocVienActionPerformed

    private void mniBangDiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniBangDiemActionPerformed
        openThongKe(0);
    }//GEN-LAST:event_mniBangDiemActionPerformed

    private void mniDiemCDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniDiemCDActionPerformed
        openThongKe(2);
    }//GEN-LAST:event_mniDiemCDActionPerformed

    private void mniDoanhThuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniDoanhThuActionPerformed
        openThongKe(3);
    }//GEN-LAST:event_mniDoanhThuActionPerformed

    private void mniHDSDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniHDSDActionPerformed
        openHuongDan();
    }//GEN-LAST:event_mniHDSDActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        this.Exit();
    }//GEN-LAST:event_formWindowClosing

    private void btnHoTroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHoTroActionPerformed
        this.openReport();
    }//GEN-LAST:event_btnHoTroActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        try {
            String data = "https://www.facebook.com/profile.php?id=100065380270425";
            QRCodeWriter qrCodeWriter = new QRCodeWriter();
            BitMatrix matrix = qrCodeWriter.encode(data, BarcodeFormat.QR_CODE, 200, 200);

            // Write to file image
            String outputFile = "./Logos/image.png";
            Path path = FileSystems.getDefault().getPath(outputFile);
            MatrixToImageWriter.writeToPath(matrix, "PNG", path);

            // new frame
            JDialog jf = new JDialog(this, true);
            ImageIcon icon = new ImageIcon("./Logos/image.png");
            JLabel labelqr = new JLabel(icon);
            labelqr.setSize(200, 200);
            jf.add(labelqr);
            jf.setSize(200, 200);
            jf.setLocationRelativeTo(null);
            jf.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
            jf.setUndecorated(false);
            jf.setVisible(true);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void lblBannerMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBannerMouseEntered

    }//GEN-LAST:event_lblBannerMouseEntered

    private void lblBannerMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBannerMouseExited

    }//GEN-LAST:event_lblBannerMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EduSys.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EduSys().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChuyenDe;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnHoTro;
    private javax.swing.JButton btnHocVien;
    private javax.swing.JButton btnKhoaHoc;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnNguoiHoc;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JToolBar.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JPopupMenu.Separator jSeparator6;
    private javax.swing.JPopupMenu.Separator jSeparator7;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel lblBanner;
    private javax.swing.JLabel lblClock;
    private javax.swing.JLabel lblGioiThieu;
    private javax.swing.JLabel lblUser;
    private javax.swing.JMenuBar mnbMain;
    private javax.swing.JMenuItem mniBangDiem;
    private javax.swing.JMenuItem mniChangePass;
    private javax.swing.JMenuItem mniDiemCD;
    private javax.swing.JMenuItem mniDoanhThu;
    private javax.swing.JMenuItem mniExit;
    private javax.swing.JMenuItem mniGTSP;
    private javax.swing.JMenuItem mniHDSD;
    private javax.swing.JMenuItem mniHocVien;
    private javax.swing.JMenuItem mniKhoaHoc;
    private javax.swing.JMenuItem mniLogIn;
    private javax.swing.JMenuItem mniLogout;
    private javax.swing.JMenuItem mniLuotNH;
    private javax.swing.JMenuItem mniNguoiHoc;
    private javax.swing.JMenuItem mniNhanVien;
    private javax.swing.JMenuItem mnuChuyenDe;
    private javax.swing.JMenu mnuManager;
    private javax.swing.JMenu mnuStatissic;
    private javax.swing.JMenu mnuSupport;
    private javax.swing.JMenu mnuSystem;
    private javax.swing.JPanel pnlFooter;
    // End of variables declaration//GEN-END:variables

    @Override
    public void run() {
        while (true) {
            Date now = new Date();
            SimpleDateFormat formatDate = new SimpleDateFormat();
            formatDate.applyPattern("hh:mm:ss aa");
            String timeNow = formatDate.format(now);
            lblClock.setText(timeNow);
            try {
                Thread.sleep(1000);
            } catch (InterruptedException ex) {
                break;
            }
        }
    }

    private void initFrame() {
        CreateFormat.formatJrame(this, "System Education Manager Course");
        new ChaoJDialog(this, true).setVisible(true);
        new DangNhapJDialog(this, true).setVisible(true);
        String name = Authentication.user.getHoTen();
        String a = Authentication.user.getVaiTro() == 1 ? "Truong Phong : " + name : "Nhân Viên :  " + name;
        lblUser.setText(a);

    }

    private void openLogin() {
        if (Authentication.user != null) {
            mess.messageNotify(this, "You is Login", "Waring");
        } else {
            new DangNhapJDialog(this, true).setVisible(true);
            changUser();
        }

    }

    private void openChangePassword() {
        if (Authentication.isLogin()) {
            new DoiMatKhauJDialog(this, true).setVisible(true);
        } else {
            mess.messageNotify(this, "Please Login", "Notify");
        }
    }

    private void Logout() {

        new DangNhapJDialog(this, true).setVisible(true);
        changUser();

    }

    private void changUser() {
        String name = Authentication.user.getHoTen();
        String a = Authentication.user.getVaiTro() == 1 ? "Truong Phong : " + name : "Nhân Viên :  " + name;
        lblUser.setText(a);
    }

    private void Exit() {
        if (mess.confirmMessage(this, "Do you want to exit?", "Exit") == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }

    private void openNhanVien() {
        if (Authentication.isLogin()) {
            new QuanLyNhanVien().setVisible(true);
        } else {
            mess.messageNotify(this, "Please Login", "Notify");
        }

    }

    private void openKhoaHoc() {
        if (Authentication.isLogin()) {
            new QuanLyKhoaHoc().setVisible(true);
        } else {
            mess.messageNotify(this, "Please Login", "Notify");
        }

    }

    private void openChuyenDe() {
        if (Authentication.isLogin()) {
            new QuanLyChuyenDe().setVisible(true);
        } else {
            mess.messageNotify(this, "Please Login", "Notify");
        }
    }

    private void openNguoiHoc() {
        if (Authentication.isLogin()) {
            new QuanLyNguoiHoc().setVisible(true);
        } else {
            mess.messageNotify(this, "Please Login", "Notify");
        }
    }

    private void openHocVien() {
        if (Authentication.isLogin()) {
            new QuanLyHocVien().setVisible(true);
        } else {
            mess.messageNotify(this, "Please Login", "Notify");
        }
    }

    private void openThongKe(int index) {
        if (Authentication.isLogin()) {
            if (index == 3 && !Authentication.isManager()) {
                mess.messageNotify(this, "You not role view turnover", "Role");
            } else {
                ThongKe tk = new ThongKe();
                tk.setVisible(true);
                tk.selectTab(index);
            }
        } else {
            mess.messageNotify(this, "Please Login", "Login");
        }
    }

    private void openGioiThieu() {
        new GioiThieuJDialog(this, true).setVisible(true);
    }

    private void openHuongDan() {
        try {
            Desktop.getDesktop().browse(new File("src\\Help\\index.html").toURI());
        } catch (Exception e) {
            mess.messageNotify(this, "Not found Website", "Error");
        }

    }

    private void openReport() {
        new ResportEmail().setVisible(true);
    }

}
