/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import DAO.ChuyenDeDAO;
import Enity.ChuyenDe;
import java.awt.Color;
import java.io.File;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.*;

/**
 *
 * @author truong
 */
public class QuanLyChuyenDe extends javax.swing.JFrame {

    DefaultTableModel modelTable = new DefaultTableModel();
    ChuyenDeDAO dao = new ChuyenDeDAO();
    ChuyenDe cd = new ChuyenDe();
    CheckData data = new CheckData();
      JFileChooser filechooser = new JFileChooser();
    int row = -1;
    MessageNotifycation mess = new MessageNotifycation();
    String linkImage = "pictureroot.png";
    // 

    /**
     * Creates new form QuanLyChuyenDe
     */
    public QuanLyChuyenDe() {
        initComponents();
        initFrame();
        initColumnTable();
        fillTable();

    }

    public void initColumnTable() {
        modelTable = (DefaultTableModel) tblList.getModel();
        modelTable.setColumnIdentifiers(new String[]{"Ma CD", "Ten CD", "Hoc Phi", "Thoi Luong", "Hinh", "Mo Ta"});
        tblList.setEnabled(true);
    }

    private boolean checkForm() {
        Valid vl = new Valid();
//        if (!data.checkIsEmpty(txtMaChuyenDe)) {
//            data.changColorLabel(false, lblerrMaChuyenDe, "MACD is not empty");
//            return false;
//        } else {
//            data.changColorLabel(true, lblerrMaChuyenDe, null);
//        }
//        if (!data.checkIsEmpty(txtTenChuyenDe)) {
//            data.changColorLabel(false, lblerrTenChuyenDe, "TenCD is not empty");
//            return false;
//        } else {
//            data.changColorLabel(true, lblerrTenChuyenDe, null);
//        }
//        if (!data.checkIsEmpty(txtthoiLuong)) {
//            data.changColorLabel(false, lblerrThoiLuong, "confirm is not empty");
//            return false;
//        } else if (!data.checkTime(txtthoiLuong.getText())) {
//            data.changColorLabel(false, lblerrThoiLuong, "Time is Interge and > 0");
//        } else {
//            data.changColorLabel(true, lblerrThoiLuong, null);
//        }
//        if (!data.checkIsEmpty(txtHocPhi)) {
//            data.changColorLabel(false, lblerrHocPhi, "Name is not empty");
//            return false;
//        } else if (!data.checkFee(txtHocPhi.getText())) {
//            data.changColorLabel(false, lblerrHocPhi, "Fee  > 10000  is number");
//            return false;
//        } else {
//            data.changColorLabel(true, lblerrHocPhi, null);
//        }
//        if(txtMoTa.getText().isEmpty()){
//            data.changColorLabel(false, lblerrMoTa, "Describe is not empty");
//            return false;
//        }else{
//            data.changColorLabel(true, lblerrMoTa, null);
//        }
            vl.multiReMatch(txtMaChuyenDe, lblerrMaChuyenDe, "id", formatTopical);
            vl.isEmpty(txtTenChuyenDe, lblerrTenChuyenDe, "name");
            vl.multiBiggerAndLower(txtthoiLuong, lblerrThoiLuong, "Time",10 , 1000);
            vl.multiBiggerAndLower(txtHocPhi, lblerrHocPhi, "Fee", 1000.0, 10000.0);
        return vl.getLoi().equals("");
    }

    private String formatTopical = "^CD\\d{5}$";

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        tabs = new javax.swing.JTabbedPane();
        pnlList = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblList = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        btnprint = new javax.swing.JButton();
        pnlUpdates = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lblImage = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtMaChuyenDe = new javax.swing.JTextField();
        txtTenChuyenDe = new javax.swing.JTextField();
        txtthoiLuong = new javax.swing.JTextField();
        txtHocPhi = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtMoTa = new javax.swing.JTextArea();
        pnlController = new javax.swing.JPanel();
        btnAdd = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnNew = new javax.swing.JButton();
        btnMove = new javax.swing.JPanel();
        btnFirst = new javax.swing.JButton();
        btnReverse = new javax.swing.JButton();
        btnNext = new javax.swing.JButton();
        btnLast = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        lblerrMaChuyenDe = new javax.swing.JLabel();
        lblerrTenChuyenDe = new javax.swing.JLabel();
        lblerrThoiLuong = new javax.swing.JLabel();
        lblerrHocPhi = new javax.swing.JLabel();
        lblerrMoTa = new javax.swing.JLabel();
        lblerrImage = new javax.swing.JLabel();
        pnlBackGround = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 255));
        jLabel1.setText("Quan Ly Chuyen De");

        tabs.setBackground(new java.awt.Color(255, 153, 0));
        tabs.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);

        tblList.setBackground(new java.awt.Color(204, 204, 255));
        tblList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblList.setEnabled(false);
        tblList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblListMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblList);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/print-icon.png"))); // NOI18N
        jButton1.setText("Print");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnprint.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/print-icon.png"))); // NOI18N
        btnprint.setText("Print");
        btnprint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnprintActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlListLayout = new javax.swing.GroupLayout(pnlList);
        pnlList.setLayout(pnlListLayout);
        pnlListLayout.setHorizontalGroup(
            pnlListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlListLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 670, Short.MAX_VALUE)
                    .addGroup(pnlListLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnprint, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(pnlListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlListLayout.createSequentialGroup()
                    .addGap(256, 256, 256)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(256, Short.MAX_VALUE)))
        );
        pnlListLayout.setVerticalGroup(
            pnlListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlListLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 439, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnprint)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pnlListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlListLayout.createSequentialGroup()
                    .addGap(227, 227, 227)
                    .addComponent(jButton1)
                    .addContainerGap(242, Short.MAX_VALUE)))
        );

        tabs.addTab("LIst", pnlList);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Hinh Logo");

        lblImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/anh3.png"))); // NOI18N
        lblImage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblImageMouseClicked(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Ma Chuyen De");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Ten Chuyen De");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Thoi Luong (Gio)");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("Hoc Phi");

        txtHocPhi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHocPhiActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setText("Mo Ta Chuyen De ");

        txtMoTa.setColumns(20);
        txtMoTa.setRows(5);
        jScrollPane2.setViewportView(txtMoTa);

        btnAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Actions-document-save-icon.png"))); // NOI18N
        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        pnlController.add(btnAdd);

        btnEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/edit-validated-icon.png"))); // NOI18N
        btnEdit.setText("Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });
        pnlController.add(btnEdit);

        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Trash-can-icon.png"))); // NOI18N
        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        pnlController.add(btnDelete);

        btnNew.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/new-file-icon.png"))); // NOI18N
        btnNew.setText("New");
        btnNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewActionPerformed(evt);
            }
        });
        pnlController.add(btnNew);

        btnFirst.setText("<<");
        btnFirst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFirstActionPerformed(evt);
            }
        });
        btnMove.add(btnFirst);

        btnReverse.setText("<");
        btnReverse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReverseActionPerformed(evt);
            }
        });
        btnMove.add(btnReverse);

        btnNext.setText(">");
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });
        btnMove.add(btnNext);

        btnLast.setText(">>");
        btnLast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLastActionPerformed(evt);
            }
        });
        btnMove.add(btnLast);

        lblerrMaChuyenDe.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblerrMaChuyenDe.setText(" ");

        lblerrTenChuyenDe.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblerrTenChuyenDe.setText(" ");

        lblerrThoiLuong.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblerrThoiLuong.setText(" ");

        lblerrHocPhi.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblerrHocPhi.setText(" ");

        lblerrMoTa.setText(" ");

        lblerrImage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblerrImage.setText(" ");

        javax.swing.GroupLayout pnlUpdatesLayout = new javax.swing.GroupLayout(pnlUpdates);
        pnlUpdates.setLayout(pnlUpdatesLayout);
        pnlUpdatesLayout.setHorizontalGroup(
            pnlUpdatesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlUpdatesLayout.createSequentialGroup()
                .addGroup(pnlUpdatesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlUpdatesLayout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlUpdatesLayout.createSequentialGroup()
                .addGroup(pnlUpdatesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlUpdatesLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblerrMoTa, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlUpdatesLayout.createSequentialGroup()
                        .addComponent(pnlController, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnMove, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlUpdatesLayout.createSequentialGroup()
                        .addGroup(pnlUpdatesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlUpdatesLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(pnlUpdatesLayout.createSequentialGroup()
                                .addGroup(pnlUpdatesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblImage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblerrImage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(pnlUpdatesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnlUpdatesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lblerrHocPhi, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(pnlUpdatesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(pnlUpdatesLayout.createSequentialGroup()
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblerrThoiLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(pnlUpdatesLayout.createSequentialGroup()
                                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 247, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblerrMaChuyenDe, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txtTenChuyenDe)
                                    .addComponent(txtthoiLuong)
                                    .addComponent(txtHocPhi)
                                    .addComponent(txtMaChuyenDe)
                                    .addGroup(pnlUpdatesLayout.createSequentialGroup()
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblerrTenChuyenDe, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addGap(84, 84, 84))
        );
        pnlUpdatesLayout.setVerticalGroup(
            pnlUpdatesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlUpdatesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlUpdatesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlUpdatesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlUpdatesLayout.createSequentialGroup()
                        .addComponent(txtMaChuyenDe, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlUpdatesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(lblerrMaChuyenDe))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtTenChuyenDe, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(pnlUpdatesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlUpdatesLayout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jLabel6))
                            .addGroup(pnlUpdatesLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblerrTenChuyenDe)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtthoiLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlUpdatesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblerrThoiLuong)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtHocPhi, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlUpdatesLayout.createSequentialGroup()
                        .addComponent(lblImage, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblerrImage)))
                .addGroup(pnlUpdatesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlUpdatesLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlUpdatesLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(lblerrHocPhi)))
                .addGap(10, 10, 10)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(pnlUpdatesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlUpdatesLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(pnlController, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnlUpdatesLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblerrMoTa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnMove, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        tabs.addTab("Update", pnlUpdates);

        pnlBackGround.setBackground(new java.awt.Color(255, 102, 0));

        javax.swing.GroupLayout pnlBackGroundLayout = new javax.swing.GroupLayout(pnlBackGround);
        pnlBackGround.setLayout(pnlBackGroundLayout);
        pnlBackGroundLayout.setHorizontalGroup(
            pnlBackGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 218, Short.MAX_VALUE)
        );
        pnlBackGroundLayout.setVerticalGroup(
            pnlBackGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tabs, javax.swing.GroupLayout.PREFERRED_SIZE, 682, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addComponent(pnlBackGround, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tabs)
                .addContainerGap())
            .addComponent(pnlBackGround, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtHocPhiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHocPhiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHocPhiActionPerformed

    private void lblImageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImageMouseClicked

        this.chosePictrue();
    }//GEN-LAST:event_lblImageMouseClicked

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        if (checkForm()) {
            this.insert();
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        if (checkForm()) {
            this.update();
        }
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        this.delete();
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewActionPerformed
        this.clearForm();
    }//GEN-LAST:event_btnNewActionPerformed

    private void btnFirstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFirstActionPerformed
        this.first();
    }//GEN-LAST:event_btnFirstActionPerformed

    private void btnReverseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReverseActionPerformed
        this.pre();
    }//GEN-LAST:event_btnReverseActionPerformed

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        this.next();
    }//GEN-LAST:event_btnNextActionPerformed

    private void btnLastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLastActionPerformed
        this.last();
    }//GEN-LAST:event_btnLastActionPerformed

    private void tblListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblListMouseClicked
        try {
            row = tblList.getSelectedRow();
        if (row != -1) {
            tblList.setRowSelectionInterval(row, row);
        }
        if (evt.getClickCount() == 2) {
            this.edit();
        }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_tblListMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        mess.print(tblList, "List Staff", "Fpoly.com");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnprintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnprintActionPerformed
       mess.print(tblList, "List Topical", "Fpoly.com");
    }//GEN-LAST:event_btnprintActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuanLyChuyenDe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuanLyChuyenDe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuanLyChuyenDe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuanLyChuyenDe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuanLyChuyenDe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnFirst;
    private javax.swing.JButton btnLast;
    private javax.swing.JPanel btnMove;
    private javax.swing.JButton btnNew;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnReverse;
    private javax.swing.JButton btnprint;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblImage;
    private javax.swing.JLabel lblerrHocPhi;
    private javax.swing.JLabel lblerrImage;
    private javax.swing.JLabel lblerrMaChuyenDe;
    private javax.swing.JLabel lblerrMoTa;
    private javax.swing.JLabel lblerrTenChuyenDe;
    private javax.swing.JLabel lblerrThoiLuong;
    private javax.swing.JPanel pnlBackGround;
    private javax.swing.JPanel pnlController;
    private javax.swing.JPanel pnlList;
    private javax.swing.JPanel pnlUpdates;
    private javax.swing.JTabbedPane tabs;
    private javax.swing.JTable tblList;
    private javax.swing.JTextField txtHocPhi;
    private javax.swing.JTextField txtMaChuyenDe;
    private javax.swing.JTextArea txtMoTa;
    private javax.swing.JTextField txtTenChuyenDe;
    private javax.swing.JTextField txtthoiLuong;
    // End of variables declaration//GEN-END:variables

    private void initFrame() {
        CreateFormat.formatJrame(this, "Quan Ly Chuyen De");
        updatestates();
    }

    public void insert() {
        cd = getForm();
        ChuyenDe cd2 = dao.selectByID(txtMaChuyenDe.getText());
        try {
            if( cd2!= null){
                mess.messageNotify(this, "You cant' the same topical", "Error");
                return;
            }
            dao.insert(cd);
            fillTable();
            this.clearForm();
            tabs.setSelectedIndex(0);
            mess.messageNotify(this, "Insert successfull", "Success");

        } catch (Exception e) {
            mess.messageNotify(this, "Insert  fail", "Error");

        }

    }

    public void update() {
        cd = getForm();
        try {
            dao.update(cd);
            fillTable();
            this.clearForm();
               tabs.setSelectedIndex(0);
            mess.messageNotify(this, "Update successfull", "Success");
        } catch (Exception e) {
            mess.messageNotify(this, "Update fail", "Error");
        }

    }

    public void delete() {
        if (!Authentication.isManager()) {
            mess.messageNotify(this, "You can't delete with employee position!", "Waring");
        } else {
            try {
                if (mess.confirmMessage(this, "Do you want to delete this  Thematic?", "Warring") == JOptionPane.YES_OPTION) {
                    dao.delete(txtMaChuyenDe.getText());
                    fillTable();
                    this.clearForm();
                       tabs.setSelectedIndex(0);
                    mess.messageNotify(this, "Delete successful", "Success");
                }
            } catch (Exception e) {
                mess.messageNotify(this, "Delete Fail", "Error");
            }
        }

    }

    public void clearForm() {
        txtMaChuyenDe.setText("");
        txtTenChuyenDe.setText("");
        txtHocPhi.setText("");
        txtthoiLuong.setText("");
        txtMoTa.setText("");
        txtMaChuyenDe.setBackground(Color.white);
        txtTenChuyenDe.setBackground(Color.white);
        txtHocPhi.setBackground(Color.white);
        txtthoiLuong.setBackground(Color.white);
        txtMoTa.setBackground(Color.white);
        lblerrMaChuyenDe.setText(" ");
        lblerrTenChuyenDe.setText(" ");
        lblerrMoTa.setText(" ");
        lblerrThoiLuong.setText(" ");
        lblerrHocPhi.setText(" ");
        lblerrImage.setText(" ");
        lblImage.setIcon(Ximage.read(linkImage, lblImage));
        
        this.clearCD();

    }

    public void edit() {
        String id = (String) tblList.getValueAt(row, 0);
        cd = dao.selectByID(id);
        setForm(cd);
        tabs.setSelectedIndex(1);
        updatestates();
    }
    

    public void first() {
        this.row = 0;
        this.edit();
    }

    public void pre() {
        if (this.row > 0) {
            this.row--;
            this.edit();
        }
    }

    public void next() {
        if (this.row > tblList.getRowCount() - 1) {
            this.row++;
            this.edit();
        }

    }

    public void last() {
        this.row = tblList.getRowCount() - 1;
        this.edit();
    }

    public void fillTable() {
        modelTable = (DefaultTableModel) tblList.getModel();
        modelTable.setRowCount(0);
        try {
            List<ChuyenDe> list = dao.getAllDate();
            list.stream().forEach((cd) -> {
                modelTable.addRow(new Object[]{cd.getMaCD(), cd.getTenCD(), cd.getHocPhi(), cd.getThoiLuong(), cd.getHinh(), cd.getMoTa()});
            });
        } catch (Exception e) {
            mess.messageNotify(this, "Query Error", "Error");
            e.printStackTrace();
        }
    }

    public void setForm(ChuyenDe cd) {
        txtMaChuyenDe.setText(cd.getMaCD());
        txtTenChuyenDe.setText(cd.getTenCD());
        txtHocPhi.setText(String.valueOf(cd.getHocPhi()));
        txtthoiLuong.setText(String.valueOf(cd.getThoiLuong()));
        txtMoTa.setText(cd.getMoTa());
        if(cd.getHinh()!=null){
            lblImage.setToolTipText(cd.getHinh());
            lblImage.setIcon(Ximage.read(cd.getHinh(),lblImage));
          
        }
        

    }

    public ChuyenDe getForm() {
        ChuyenDe cd = new ChuyenDe();
        cd.setMaCD(txtMaChuyenDe.getText());
        cd.setTenCD(txtTenChuyenDe.getText());
        cd.setHocPhi(Float.parseFloat(txtHocPhi.getText()));
        cd.setThoiLuong(Integer.parseInt(txtthoiLuong.getText()));
        cd.setMoTa(txtMoTa.getText());
         cd.setHinh(lblImage.getToolTipText());
        return cd;
    }

    public void updatestates() {
        boolean edit = (this.row >= 0);
        boolean first = (this.row == 0);
        boolean last = (this.row == tblList.getRowCount() - 1);
        // States form
        if (Authentication.user.getVaiTro() == 1) {
            btnAdd.setEnabled(true);
            btnEdit.setEnabled(true);
            btnDelete.setEnabled(true);
        } else {
            btnDelete.setEnabled(false);
        }
        // States
        btnFirst.setEnabled(edit && !first);
        btnReverse.setEnabled(edit && !first);
        btnNext.setEnabled(edit && !last);
        btnLast.setEnabled(edit && !last);
    }

    public void clearCD() {
        ChuyenDe cd = new ChuyenDe();
        setForm(cd);
        row = -1;
        this.updatestates();
    }

//    public void choseImage() {  
//        filechooser.setCurrentDirectory(new File("./src/img"));
//        filechooser.setDialogTitle("Chose Image");
//        if (filechooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
//            File file = filechooser.getSelectedFile();
//            Ximage.save(file); // luu hinh
//            ImageIcon icon =reSizeImgae(file.getAbsolutePath()); // doc hinh       
//            lblImage.setIcon(icon);
//            lblImage.setToolTipText(LinkImage(file.getName())); // lay ten hinh vao tooltext de luu vao csdl
//        }
//    }
//
//    private ImageIcon reSizeImgae(String path) {
//        ImageIcon myImage = new ImageIcon(path);
//        Image img = myImage.getImage();
//        Image newimg = img.getScaledInstance(lblImage.getWidth(), lblImage.getHeight(), Image.SCALE_SMOOTH);
//        ImageIcon image = new ImageIcon(newimg);
//        return image;
//    }
    public void chosePictrue(){
        if(filechooser.showOpenDialog(this)==JFileChooser.APPROVE_OPTION){
            File file = filechooser.getSelectedFile();
            Ximage.save(file);
            System.out.println(file.getName());
            ImageIcon icon = Ximage.read(file.getName(),lblImage);
            lblImage.setIcon(icon);
            lblImage.setToolTipText(file.getName());
        }
    }
}
